### ISSUE TITLE
Support RHEL

### ISSUE THREAD

**Issue by PierreR** [mietek/halcyon#20]
From the install script I can see that `fedora` or `centos`. Is there some support for RHEL ?

Thx

**Comment by mietek** [comment]
There is very little in Halcyon which is OS-specific:
1. The install script, which ensures the necessary OS packages are installed prior to use
2. Support for the [`HALCYON_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_extra_os_packages) and [`HALCYON_SANDBOX_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_sandbox_extra_os_packages) options, for installing native OS packages during use

I haven’t done any testing on RHEL, but as I understand CentOS is based on RHEL.  What happens when you try running the install script?

You can also install Halcyon manually:
1. See the install script for the necessary OS packages to install
2. Clone the Halcyon source repository to your preferred location
3. Make sure `/app` is writeable by your intended user
4. Add `source <( path/to/halcyon/halcyon paths )` to your `.bash_profile`

**Comment by PierreR** [comment]
I haven't tried to run the setup script but looking at [platform.sh](https://github.com/mietek/bashmenot/blob/master/src/platform.sh#L66) I don't think it would work.

CentOS is pretty much a recompilation (minus specific proprietary RHEL software) so I guess it would install just fine. It is a matter of changing the `platform script`. 

I will try your suggestions and let you know.

Thanks for your help.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/049d22358c58d9dbc9eb280c9bef1310847d4ea3, the setup script will now report your platform identifier.  Can you tell me what it looks like on your RHEL system?

**Comment by PierreR** [comment]
The output of `detect_platform` is `linux-x86_64`

As another info:
```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 6.6 (Santiago)
```

**Comment by mietek** [comment]
Thanks.  I don’t have a good way to test RHEL at the moment, but I’ll look into it in the future.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/011a4b8e716b5fbb6f072e991dfbd2507ef2d0ee, RHEL 6 and 7 are now supported.

**Comment by PierreR** [comment]
I will try it. Thanks.

There is something though that I find a bit cumbersome with the setup script. It requires root or `sudo` access.

I have all `halcyon` operations done by an unprivileged user and I don't want it to have `sudo` privileges. 

In that regard, I would love the setup script to work if HALCYON_BASE is already created (but empty) and owned by the unprivileged user (at that point `sudo` is not needed).

In the meanwhile I am just cloning the repo myself which is not a big deal.

Cheers

**Comment by mietek** [comment]
Note the setup script ensures `halcyon` will not need `sudo`.

Thanks for your suggestion.  Can you open a separate issue, please?

**Comment by PierreR** [comment]
Thanks for the detailed answer.

I will open a new issue
