### ISSUE TITLE
Install fails on CentOS 6 using a sudo user

### ISSUE THREAD

**Issue by PierreR** [mietek/halcyon#22]
I have managed to install halcyon using root.

I then had a go using another user (with sudo privilege). The `setup` step was a success but  when I tried `halcyon install` I have got:
```
Restoring GHC directory
       Extracting halcyon-ghc-7.8.4.tar.gz... done, 699MB
touch: cannot touch `/var/tmp/halcyon-cache/halcyon-ghc-7.8.4.tar.gz': Permission denied
```
I even tried `sudo /app/halcyon/halcyon install` but then I have got another error:

```
-----> Self-updating bashmenot... done, a7e57d3
-----> Self-updating Halcyon... done, 8da0d8f
   *** ERROR: Unexpected GHC user package database

       To disable the GHC user package database:
       $ mv ~/.ghc ~/.ghc.original
```
I am quite confused about how I am supposed to use `halcyon`. Does it need to be installed by `root` ? Should I then manually change the permission on `app` to be able to run it using a non-privilege user ?

Thanks for your help.

**Comment by mietek** [comment]
You shouldn’t be using `sudo` to run or install Halcyon.

The [Halcyon tutorial](https://halcyon.sh/tutorial/#set-up) shows how to install Halcyon as a non-root user with `sudo` privilege:
```
$ source <( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )
```

Within the setup script, `sudo` is only used to:

1. Install the necessary OS packages
2. Create `/app` and ensure it’s owned by the current user

If you installed Halcyon as `root`, `/app` would end up owned by `root`.  If you also ran `halcyon install` as `root`, [`HALCYON_CACHE`](https://halcyon.sh/reference/#halcyon_cache) would also end up owned by `root`.  This explains the first error message.

The second error message is unrelated to permissions.  Halcyon doesn’t support running with a non-empty GHC user package database, because of a Cabal issue (https://github.com/haskell/cabal/issues/2400).  To use Halcyon, either remove or disable your GHC user package database, which is located in your home directory, and named `.ghc`.

I can help walk you through the setup process.  Let’s chat in `#haskell-deployment` on [freenode](https://freenode.net).

**Comment by PierreR** [comment]
Yep, when I restart over I just remove /app completely but I had to remove the cache as well (/var/tmp/halcyon-cache).

I have just done so and it seems to work fine.

I will have to go out in a minute so I won't be able to chat. 

Thanks for your help.

**Comment by mietek** [comment]
Good. Indeed, that’s all you need to do in order to remove/reinstall Halcyon.

**Comment by PierreR** [comment]
Another quick question if you don't mind.

How do I install a library globally for instance `turtle` ? I have tried `halcyon install turtle` which completes with success but then it hasn't been registered yet by ghc. So it is not in `ghc-pkg list`.

**Comment by mietek** [comment]
@PierreR: Please continue the discussion in https://github.com/mietek/halcyon/issues/23.
