### ISSUE TITLE
Equivalent of `cabal install xxx --configure-option=` in halcyon install ?

### ISSUE THREAD

**Issue by PierreR** [mietek/halcyon#24]
What is the equivalent of doing
`cabal install hruby --configure-option=--
rubyversion=18 --rubylib=ruby --rubyinc=/usr/lib64/ruby/1.8/x86_64-linux/` when using `halcyon install`?

A bit of context: I am trying to build [`language-puppet`](http://hackage.haskell.org/package/language-puppet). Using a dinosaur OS (CentOS 6) I need to build the hruby dependency with the above command (it works fine in a cabal sandbox).

I had a go with "HALCYON_EXTRA_CONFIGURE_FLAGS" but without success.

This is not a big issue because I can use `cabal sandbox` to build the executable but succeeding an `halcyon install` would be nice.

**Comment by mietek** [comment]
Using Halcyon to install `hruby` isn’t the best option, because Halcyon isn’t intended to install libraries (https://github.com/mietek/halcyon/issues/23).  However, you can do it, and [`HALCYON_EXTRA_CONFIGURE_FLAGS`](https://halcyon.sh/reference/#halcyon_extra_configure_flags) is the right option to use:
```
$ halcyon install hruby --extra-configure-flags='--configure-option=--rubyversion=18 --configure-option=--rubylib=ruby --configure-option=--rubyinc=/usr/lib64/ruby/1.8/x86_64-linux'
```

Now, installing `language-puppet` is exactly what Halcyon is for.  Since `hruby` is one of the dependencies to be installed in the sandbox, [`HALCYON_SANDBOX_EXTRA_CONFIGURE_FLAGS`](https://halcyon.sh/reference/#halcyon_sandbox_extra_configure_flags) seems like the right option to use:
```
$ halcyon install language-puppet --sandbox-extra-configure-flags='--configure-option=--rubyversion=18 --configure-option=--rubylib=ruby --configure-option=--rubyinc=/usr/lib64/ruby/1.8/x86_64-linux'
```

Unfortunately, while this would get `hruby` built, Cabal would apply the `--configure-option` flags to all dependencies, preventing the `network` package from building.  The solution is to create a Cabal sandbox, install `hruby` with the right flags, then install the remaining dependencies.

Halcyon provides the [`HALCYON_SANDBOX_PRE_BUILD_HOOK`](https://halcyon.sh/reference/#halcyon_sandbox_pre_build_hook), which runs after a sandbox is created, and before dependencies are installed.  This is exactly what we need here:
```bash
#!/usr/bin/env bash

source "${HALCYON_DIR}/src.sh"


sandbox_pre_build_hook () {
	local tag source_dir constraints
	expect_args tag source_dir constraints -- "$@"

	local -a opts_a
	opts_a=()
	opts_a+=( 'hruby-0.2.8' )
	opts_a+=( --configure-option='--rubyversion=18' )
	opts_a+=( --configure-option='--rubylib=ruby' )
	opts_a+=( --configure-option='--rubyinc=/usr/lib64/ruby/1.8/x86_64-linux' )

	sandboxed_cabal_do "${source_dir}" install "${opts_a[@]}" 2>&1 | quote || return 1
}


sandbox_pre_build_hook "$@"
```

To ensure both invocations of `cabal install` install compatible packages, we need to declare version constraints — either in a `cabal.config` file, which you can generate with `cabal freeze`, or with [`HALCYON_CONSTRAINTS`](https://halcyon.sh/reference/#halcyon_constraints).

Both the constraints and the sandbox pre-build hook can be included as files with the app:
- [.halcyon/constraints](https://github.com/mietek/language-puppet/blob/centos6/.halcyon/constraints)
- [.halcyon/sandbox-pre-build-hook](https://github.com/mietek/language-puppet/blob/centos6/.halcyon/sandbox-pre-build-hook).

With these files in place, and `ruby-devel` already on the system, you can now install `language-puppet` with Halcyon:
```
$ yum install -y ruby-devel
$ halcyon install https://github.com/mietek/language-puppet#centos6
```

The next step would be to use [`HALCYON_SANDBOX_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_sandbox_extra_os_packages) to declare `ruby-devel` for automatic installation.  You’ll probably need to reference `/app/sanbox/usr/lib64` in the `--rubyinc` flag.  Let me know if you run into trouble.

**Comment by PierreR** [comment]
I had a go with the latest master version but I have got a permission error.

As user 'jenkins':

halcyon install https://github.com/PierreR/language-puppet.git#centos6

```
-----> Creating sandbox
-----> Executing sandbox pre-build hook
       /app/halcyon/src/sandbox.sh: line 344: /tmp/halcyon-source-language-puppet-1.0.2.nzd4kBd1L6/.halcyon/sandbox-pre-build-hook: Permission denied
   *** ERROR: Failed to execute sandbox pre-build hook

```
If I check '/tmp/halcyon-source-language-puppet-1.0.2.nzd4kBd1L6/.halcyon/sandbox-pre-build-hook' it is owned by the running user.

`/app` is recursively owned by the jenkins user:
```
ls -la /app/halcyon/
total 48
drwxr-xr-x  6 jenkins jenkins 4096 Feb  7 18:11 .
drwxr-xr-x 10 jenkins jenkins 4096 Feb  8 22:55 ..
drwxrwxr-x  2 jenkins jenkins 4096 Feb  7 17:55 bin
drwxrwxr-x  8 jenkins jenkins 4096 Feb  7 18:11 .git
-rw-rw-r--  1 jenkins jenkins    4 Feb  7 17:55 .gitignore
-rwxrwxr-x  1 jenkins jenkins  170 Feb  7 17:55 halcyon
drwxrwxr-x  3 jenkins jenkins 4096 Feb  7 17:55 lib
-rw-rw-r--  1 jenkins jenkins 1853 Feb  7 17:55 README.md
-rw-rw-r--  1 jenkins jenkins 6026 Feb  7 17:55 setup.sh
drwxrwxr-x  2 jenkins jenkins 4096 Feb  8 23:06 src
-rw-rw-r--  1 jenkins jenkins 2478 Feb  7 17:55 src.sh
```
Any idea ?

**Comment by mietek** [comment]
It’s not the user.  You just need to `chmod +x .halcyon/sandbox-pre-build-hook`.  Remember to commit the change, too.

**Comment by PierreR** [comment]
It works fine ! I have managed to build `language-puppet`.

Thanks for your help.
