### ISSUE TITLE
Use reduced redundancy storage for S3 private storage

### ISSUE THREAD

**Issue by jspahrsummers** [mietek/halcyon#33]
From the [Using Reduced Redundancy Storage](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRRS.html) documentation:

> In order to reduce storage costs, you can use reduced redundancy storage for noncritical, reproducible data at lower levels of redundancy than Amazon S3 provides with standard storage. The lower level of redundancy results in less durability and availability, but in many cases, the lower costs can make reduced redundancy storage an acceptable storage solution.

Since Halcyon sandboxes and apps can always be rebuilt from scratch in the event of data loss on S3, it seems like this should be the default.

**Comment by mietek** [comment]
Thanks.  There should certainly be an option to do this, and perhaps indeed it should be the default.

I can see at least one case in which it shouldn’t, though.  Halcyon can be used to distribute binary versions of your app — just install it once on each supported platform, so that install directory archives are in your private storage, then take the URL of your S3 bucket and give it to people to use as their [`HALCYON_PUBLIC_STORAGE_URL`](https://halcyon.sh/reference/#halcyon_public_storage_url).

**Comment by jspahrsummers** [comment]
Ah, interesting. It does sound like an option would make sense, then.

**Comment by jspahrsummers** [comment]
I [found out](https://twitter.com/jspahrsummers/status/566408639443783680) today that Reduced Redundancy Storage _always_ results in charges, even if you would otherwise qualify for the Free Tier, so I don't think defaulting to this is a good idea after all. :confused:

**Comment by mietek** [comment]
Do you have a supporting link to AWS documentation?

**Comment by jspahrsummers** [comment]
It's apparently in http://aws.amazon.com/free/faqs/:

> **Does the AWS free tier include Amazon S3 Reduced Redundancy Storage (RRS)?**
> No, the AWS free tier does not include Amazon S3 RRS storage. The AWS free tier includes 5 GB of Amazon S3 standard storage, which offers the highest Amazon S3 durability.

(I don't know why they would expect that to get read ahead of time.)

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
