### ISSUE TITLE
Support static linking

### ISSUE THREAD

**Issue by noteed** [mietek/halcyon#51]
Hi,

I was wondering if supporting building statically linked executables might be a stated goal of Halcyon.

Thanks!

**Comment by mietek** [comment]
While there is currently no additional support for building statically linked executables, as far as I know, nothing should prevent you from doing so.  Have you ran into any specific problems?

**Comment by mietek** [comment]
@noteed: Ping?

**Comment by noteed** [comment]
Sorry I've been quite busy. I have to look at it again but I think halcyon
comes with .so shared libraries, but no .a library. I think that when I
installed apt-get provided libraries I could use the static option of ghc.

**Comment by mietek** [comment]
Halcyon doesn’t use any shared libraries of its own, but it does use official GHC bindists, which require a number of shared libraries to be available on the system, such as `libgmp.so` and `libtinfo.so`.

There are no official statically-linked GHC bindists, so using a statically-linked GHC would require building GHC from source (https://github.com/mietek/halcyon/issues/8).

However, I’m not sure if it’s necessary to use a statically-linked GHC in order to build statically-linked executables. Have you found otherwise?

**Comment by mietek** [comment]
@noteed: ping

**Comment by noteed** [comment]
@mietek I'll get back to you soon.

**Comment by mietek** [comment]
Closing as inactive. Please comment when needed.
