### ISSUE TITLE
Installation wasn't straightforward

### ISSUE THREAD

**Issue by feuerbach** [mietek/halcyon#56]
Here's my experience with installing halcyon:

```
$ source <( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )
...
-----> Installing Halcyon... done, 4305c9c
-----> Installing bashmenot... done, 5165edd
   *** ERROR: Unexpected GHC user package database

       To disable the GHC user package database:
       $ mv ~/.ghc ~/.ghc.original
-----> Extending .bash_profile
```

First, it wasn't obvious whether the installation was successful and all I had to do was to move out the ghc database, or did I have to reinstall. The halcyon executable wasn't there, so I reinstalled:

```
$ source <( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )
-----> Welcome to Halcyon
   *** ERROR: Unexpected existing /app
   *** ERROR: Failed to install Halcyon
```

So I needed to go and remove `/app`, and only then did the installation succeed.

Here are some ideas how this could be improved:

* on error, indicate what the next actions should be (e.g. whether I should reinstall)
* if there's no way to proceed other than wiping out `/app`, perhaps the script could do that itself

**Comment by mietek** [comment]
Thanks for the report.

Disallowing a non-empty GHC user package database was introduced recently due to https://github.com/mietek/halcyon/issues/5, as an attempt to work around the underlying https://github.com/haskell/cabal/issues/2400.  It turns out more people are affected by the workaround than by the actual issue.  I’m planning to turn the error into a warning, and make extending `.bash_profile` optional (https://github.com/mietek/halcyon/issues/46).

The setup actually succeeded, but the error prevented `source <( halcyon paths )` from setting up the environment, which is why `halcyon` wasn’t in your `PATH`.  I didn’t expect this, so that’s a bug.  Indeed, the script could also clearly say when setup succeeded.

I’m not comfortable automatically removing an existing `/app`, because it may have been created for another purpose.

**Comment by mietek** [comment]
With https://github.com/mietek/halcyon/commit/962102a38316f8b6f51484414d4298207bc7f9be, the GHC user package DB error is now a warning, and shouldn’t interfere with `halcyon paths`, as it won’t appear until Halcyon needs to perform a build.

The setup script is due further improvements, but for now, should at least clearly say:
```
-----> Halcyon installed
```
