### ISSUE TITLE
c2hs fails to install from sandbox-extra-apps

### ISSUE THREAD

**Issue by mtolly** [mietek/halcyon#82]
An app I'm trying to set up for Halcyon requires `c2hs`, and also `alex` and `happy`. `c2hs` also needs `alex` and `happy` as part of its own build process (for the `language-c` package). I've listed all 3 tools in my `.halcyon/sandbox-extra-apps`, and it installs `alex` and `happy` first. But then it fails to install `c2hs` because it can't see either of those two.

    Downloading language-c-0.4.7...
    Configuring language-c-0.4.7...
    cabal: The program 'happy' is required but it could not be found.
    Failed to install language-c-0.4.7
    cabal: Error: some packages failed to install:
    language-c-0.4.7 failed during the configure step. The exception was:
    ExitFailure 1

**Comment by mietek** [comment]
Halcyon treats each sandbox extra app as self-contained. Therefore, you need to declare _alex_ and _happy_ as sandbox extra apps for _c2hs_, and install _c2hs_ using the [sandbox pre-build hook](https://halcyon.sh/reference/#halcyon_sandbox_pre_build_hook).

Since this is a bit tricky, I’ve now created an example project to guide you, [_halcyon-recursive-example_](https://github.com/mietek/halcyon-recursive-example).  Note the expected [build output](https://gist.github.com/mietek/d4682d7df1ac8eb4d318) shows each app is built only once.

Let me know if this helps.

**Comment by mietek** [comment]
@mtolly: ping

**Comment by mtolly** [comment]
Looks good, thanks for the help!
